  name: OpenMRS CI                                                                                                                                   
                  
  on:
    push:
      branches: [gha]
    pull_request:
      branches: [gha]
    release:                                                                                                                                         
      types: [created]
                                                                                                                                                     
  jobs:           
    build:
      uses: wikumChamith/openmrs-contrib-gha-workflows/.github/workflows/build-frontend-module.yml@build-frontend
      with:                                                                                                                                          
        node_version: '20'
        pre_verify_command: 'yarn check-translations'                                                                                                
        build_command: 'yarn turbo build'                                                                                                            
      secrets:                                                                                                                                       
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}      
